# Workflow to deploy a Node.js app using npm start
name: Deploy Node.js site to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build and deploy job
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Adjust based on your project's requirements

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Ensure required files exist
      - name: Validate project setup
        run: |
          if [ ! -f "package.json" ]; then echo "package.json not found"; exit 1; fi

      # Step 5: Start the server to ensure it works (Optional)
      - name: Run npm start (Optional Test)
        run: npm start &
        env:
          NODE_ENV: production

      # Step 6: Upload the site content to GitHub Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./ # Upload the entire repository or static content path

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Step 1: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
