name: Deploy PM2 App

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Adjust to the version your app requires

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Start the app with PM2
      - name: Start application
        run: npm start

      # Step 5: Confirm PM2 process is running
      - name: List PM2 processes
        run: pm2 list
